## -*- coding: utf-8 -*-
##
## Snakefile
##
## This file is part of https://github.com/INM-6/microcircuit-PD14-model
## 
## SPDX-License-Identifier: CC-BY-NC-SA-4.0
##

configfile: "config.yaml"
MODELS = config["MODELS"]

rule all:
	input:
		expand("ModelDescription_{MODEL}.pdf", MODEL=MODELS)

rule compile_tex_source:
	input:
		'ModelDescription_{MODEL}.tex',
		'figures/NetworkSketch_{MODEL}.pdf'
	output:
		'ModelDescription_{MODEL}.pdf'
	run:
		shell('pdflatex {input}[0]')
		shell('pdflatex {input}[0]')      

rule convert_network_sketch_to_pdf:
	input:
		expand("figures/NetworkSketch_{MODEL}.fodg", MODEL=MODELS)

	output:
		expand("figures/NetworkSketch_{MODEL}.pdf", MODEL=MODELS)
	run:
		shell('libreoffice --convert-to pdf:draw_pdf_Export {input} --outdir figures')

rule generate_connectivity_matrix:
	input:
		"figures/connectivity_microcircuit-PD14-model.py"

	output:
		"figures/connectivity_microcircuit-PD14-model.svg"

	run:
		shell("python {input}")
		shell("mv connectivity_microcircuit-PD14-model.svg figures")
		print("WARNING: %s needs to be manually integrated into figures/NetworkSketch_microcircuit-PD14-model.fodg" % output)

rule clean:
	input:
		expand("figures/NetworkSketch_{MODEL}.pdf", MODEL=MODELS)
	run:
		shell("rm -f *~ *.log *.aux *.bbl *.blg *.idx *.ilg *.ind *.lof *.out *.pfg *.toc *.soc *.nav *.snm *.bcf *.xml *blx.bib")
		shell("rm {input}")
